apiVersion: v1
kind: Namespace
metadata:
  name: hcloud-csi-rwx
  labels:
    app.kubernetes.io/name: hcloud-csi-rwx
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
