apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hcloud-csi-rwx
provisioner: hcloud-csi-rwx
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  backingStorageClass: hcloud-volumes
